server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# example values
indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
      httpRequestDelay: 500
    - url:  http://radiomv.ru/
      name: Radio.MV
      httpRequestDelay: 500
    - url: https://nopaper.ru
      name: NoPaper.Ru
      httpRequestDelay: 500

# Jsoup Connection values
connection-headers:
  userAgent: 4eSearchBot
  referrer: https://www.google.com
